use anchor_lang::prelude::*;

#[constant]
pub const ADMIN_ROLE: &[u8] = b"ADMIN_ROLE";
pub const OPERATOR_ROLE: &[u8] = b"OPERATOR_ROLE";
pub const LOCKER_ACCOUNT: &[u8] = b"LOCKER_ACCOUNT";
pub const SEED_ROUND_ACCOUNT: &[u8] = b"SEED_ROUND_ACCOUNT";
pub const PRIVATE_ROUND_ACCOUNT: &[u8] = b"PRIVATE_ROUND_ACCOUNT";
pub const PUBLIC_SALE_ACCOUNT: &[u8] = b"PUBLIC_SALE_ACCOUNT";
pub const FOUNDING_TEAM_ACCOUNT: &[u8] = b"FOUNDING_TEAM_ACCOUNT";
pub const ADVISORS_ACCOUNT: &[u8] = b"ADVISORS_ACCOUNT";
// pub const LIQUIDITY_ACCOUNT: &[u8] = b"LIQUIDITY_ACCOUNT";
pub const TREASURY_ACCOUNT: &[u8] = b"TREASURY_ACCOUNT";
pub const ECOSYSTEM_ACCOUNT: &[u8] = b"ECOSYSTEM_ACCOUNT";
